name             "timezone-ii_test"
maintainer       "Lawrence Leonard Gilbert"
maintainer_email "larry@L2G.to"
license          "Apache 2.0"
description      "Cookbook for kitchen test"
version          "0.0.0"
